run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 140

  goimports:
    local-prefixes: pr-reviewer-service

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - goconst
    - dupl
    - lll
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gocognit
    - funlen
    - whitespace
    - wsl
    - gci
    - godot
    - nolintlint

  disable:
    - exhaustive
    - exhaustivestruct
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - wrapcheck
    - nlreturn

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit

    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
